### ISSUE TITLE
the platelet's type?

### ISSUE THREAD

**Issue by keqinhan** [dmontgomery016/clotFoam#3]
In the every case of tutorials, there are three platelets, specifically, unactivated platelet, activated platelets and bound platelets. However, in the code file of ClotFoam, in the file called species platelet, there are four types platelet, whether there are some mistakes?

**Comment by ghost** [comment]
In the zero directory there are two platelet species: `plt_Pmu` is mobile unactivated and `plt_Pma` is mobile unactivated.  The `pltBound_S1b` species is a biochemical species that is bound to platelet surfaces as described in the [SoftwareX paper](https://doi.org/10.1016/j.softx.2023.101483).  

I apologize for the confusion about the other two platelet species.  I did some tricks so there are less required fields in the `0` directory to make it easier to adapt for new geometries.  If you look at [line #245](https://github.com/d-montgomery/clotFoam/blob/487c93165ce6bf8b702d8d127e0c4669cc620ab7/clotFoam/createFields.H#L245) in the `createFields.H` file in the source code, you will see that the other two platelet species (`plt_Pba` and `plt_Pbse`) are initialized as `volScalarFields` using a copy constructor of `Plt.field[1]` which is the `plt_Pma` species. The copy constructor is only used if there is no `plt_Pba` file located in the `0` directory (i.e. `READ_IF_PRESENT`). 

Note: Many of the species in the tutorials have the same initial condition and boundary condition, which is why this method works.
